### PR TITLE
Adds Code-Exporter to WPGraphiQL

### PR DESCRIPTION
**Pull request by henrikwirth**
Solves this Issue: #17 

Simply adds the [graphiql-code-exporter](https://github.com/OneGraph/graphiql-code-exporter) to WPGraphiQl. 

I made use of this approach: https://github.com/gatsbyjs/gatsby/pull/17120
For me it seems to work properly, but any reviews and tests will be highly welcome :)

How it looks: 
image

### CODE REVIEW

**Comment by jasonbahl** [comment]
@henrikwirth this is sweet! Good stuff! I just returned from 2 weeks out with almost no internet access, so I'm catching up on things. Plan to review this shortly!

**Comment by jasonbahl** [comment]
@henrikwirth this looks great! I'm going to make one change and have the "language" be "Gatsby" instead of "JavaScript" for this as I think the dropdown makes more sense to be "Gatsby > StaticQuery" vs "JavaScript > StaticQuery"

We can add things like "Apollo > Query Component" examples and "Apollo > Mutation Component" examples, etc too. 

Then potentially raw JavaScript examples as well.

**Comment by jasonbahl** [comment]
I'll push a quick change and merge.

**Comment by henrikwirth** [comment]
Good change 👍

**Pull request merged**
